# Generated by Django 4.2.6 on 2023-10-31 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentprofile', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='studentprofile',
            new_name='profilesection',
        ),
    ]
