# Generated by Django 4.2.2 on 2023-10-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdmissionPortal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionenquiry',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='city',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='course',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='state',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='university',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='admissionenquiry',
            name='zip',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='admissionenquiry',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
